In [52]:
from google.colab import drive
from numpy import array
from pandas import read_csv
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.neighbors import NearestCentroid
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
drive.mount ("mnt")


class Clasificador():

  def __init__ (self, ruta_de_archivo):
    #inicializa el DataFrame de donde recupera datos
    self.ruta_de_archivo = read_csv(ruta_de_archivo)
    #matriz que contiene los datos de cada diagnostico
    self.x = array(self.ruta_de_archivo.iloc[:,2:])
    #lista que contiene los dignosticos
    self.y = list(self.ruta_de_archivo['diagnosis'])
    #divide los datos en una proporcion 70\30 para entrenamiento\prueba
    self.x_train, self.x_test, self.y_train, self.y_test=(train_test_split(
                                                          self.x, self.y,
                                                          test_size = 0.30,
                                                          random_state = 42))

  def log_reg(self):
    #define clf como el clasificador de regresion logistica
    clf = LogisticRegression()
    #entrena el algoritmo
    clf.fit(self.x_train, self.y_train)
    #predicciones del algoritmo
    f = clf.predict(self.x_test)
    #resultados del entrenamiento y pueba
    print('precisión Regresión logística,:', accuracy_score(self.y_test, f))
    print('\nMatriz de confusion:\n', confusion_matrix(self.y_test, f),'\n')

  def KN_neighbors(self):
    #define clf como el clasificador de K-Nearest Neighbors
    clf = NearestCentroid()
    #entrena el algoritmo
    clf.fit(self.x_train, self.y_train)
    #predicciones del algoritmo
    f = clf.predict(self.x_test)
    #resultados del entrenamiento y pueba
    print('precisión de K-Nearest neighbors:', accuracy_score(self.y_test, f))
    print('\nMatriz de confusion:\n', confusion_matrix(self.y_test, f),'\n')

  def SVM_SVC(self):
    #define clf como el clasificador de SVM
    clf = SVC()
    #entrena el algoritmo
    clf.fit(self.x_train, self.y_train)
    #predicciones del algoritmo
    f = clf.predict(self.x_test)
    #resultados del entrenamiento y pueba
    print('precisión de SVM:', accuracy_score(self.y_test, f))
    print('\nMatriz de confusion:\n', confusion_matrix(self.y_test, f),'\n')

  def Arb_Dec(self):
    #define clf como el clasificador de Arboles de Decision
    clf = DecisionTreeClassifier()
    #entrena el algoritmo
    clf.fit(self.x_train, self.y_train)
    #predicciones del algoritmo
    f = clf.predict(self.x_test)
    #resultados del entrenamiento y pueba
    print('precisión de Árboles de decisión:', accuracy_score(self.y_test, f))
    print('\nMatriz de confusion:\n', confusion_matrix(self.y_test, f),'\n')

  def Ran_Forest(self):
    #define clf como el clasificador Random Forest
    clf = RandomForestClassifier()
    #entrena el algoritmo
    clf.fit(self.x_train, self.y_train)
    #predicciones del algoritmo
    f = clf.predict(self.x_test)
    #resultados del entrenamiento y pueba
    print('precisión de Random Forest:', accuracy_score(self.y_test, f))
    print('\nMatriz de confusion:\n', confusion_matrix(self.y_test, f),'\n')

def main():

  P = Clasificador('/content/mnt/MyDrive/cancer.csv')

  P.log_reg()
  P.KN_neighbors()
  P.SVM_SVC()
  P.Arb_Dec()
  P.Ran_Forest()

if __name__ == '__main__':
 main()




Drive already mounted at mnt; to attempt to forcibly remount, call drive.mount("mnt", force_remount=True).
precisión Regresión logística,: 0.98

Matriz de confusion:
 [[89  0]
 [ 3 58]] 

precisión de K-Nearest neighbors: 0.9

Matriz de confusion:
 [[89  0]
 [15 46]] 

precisión de SVM: 0.92

Matriz de confusion:
 [[88  1]
 [11 50]] 



/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


precisión de Árboles de decisión: 0.8933333333333333

Matriz de confusion:
 [[81  8]
 [ 8 53]] 

precisión de Random Forest: 0.9666666666666667

Matriz de confusion:
 [[88  1]
 [ 4 57]] 

